// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqxbDD2so7ukcZO84aYNKYwMHHvgVA4_w',
    appId: '1:272916313574:web:002537cf867e46325cd227',
    messagingSenderId: '272916313574',
    projectId: 'campusconnect-48d5e',
    authDomain: 'campusconnect-48d5e.firebaseapp.com',
    storageBucket: 'campusconnect-48d5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0jeiYfcs6Pm42QggHYgaxx_f7En8ja8A',
    appId: '1:272916313574:android:0a3fc7b16aa210475cd227',
    messagingSenderId: '272916313574',
    projectId: 'campusconnect-48d5e',
    storageBucket: 'campusconnect-48d5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYqogj7z0C7is1pGHpfq-FZsL73rdJWQE',
    appId: '1:272916313574:ios:fbac8e522d51a7cc5cd227',
    messagingSenderId: '272916313574',
    projectId: 'campusconnect-48d5e',
    storageBucket: 'campusconnect-48d5e.appspot.com',
    iosClientId: '272916313574-5q0f1vm46k5vsrva8rof2j5bb03l84eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYqogj7z0C7is1pGHpfq-FZsL73rdJWQE',
    appId: '1:272916313574:ios:fbac8e522d51a7cc5cd227',
    messagingSenderId: '272916313574',
    projectId: 'campusconnect-48d5e',
    storageBucket: 'campusconnect-48d5e.appspot.com',
    iosClientId: '272916313574-5q0f1vm46k5vsrva8rof2j5bb03l84eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnectApp',
  );
}
